import Foundation

/// Plugin-based agents whose hook surface is a generated source file Pedals
/// owns outright: opencode (JS plugin under Bun) and the omp/pi pair
/// (TypeScript extensions sharing one template). The generated code is inert
/// on failure — it spawns the reporter detached, writes one small JSON to
/// stdin, and swallows every error so it can never crash or block the host
/// agent. No env guard is needed: Pedals is system-wide.
extension HookInstaller {
    // MARK: - opencode

    /// `~/.config/opencode/plugins/pedals-presence.js`. Mapping: plugin load →
    /// session-start, tool.execute.before → busy, permission.ask → ask,
    /// session.idle → stop (opencode has no final message), permission.replied
    /// → busy, dispose → session-end. tool.execute.after is deliberately
    /// unmapped in our per-turn model.
    enum OpenCode {
        static let marker = "// pedals-managed-hook"

        static func path(home: URL) -> String {
            home.appendingPathComponent(".config", isDirectory: true)
                .appendingPathComponent("opencode", isDirectory: true)
                .appendingPathComponent("plugins", isDirectory: true)
                .appendingPathComponent("pedals-presence.js").path
        }

        static func canonicalData(reporterPath: String) -> Data {
            let reporter = escapeDoubleQuoted(reporterPath)
            let source = """
            \(marker)
            // Generated by Pedals — `pedals hooks uninstall opencode` removes this file.
            // opencode runs plugins under Bun; node:child_process gives us stdin control.
            import { spawn } from "node:child_process";

            const REPORTER = "\(reporter)";

            function report(event, extra) {
              try {
                const payload = JSON.stringify({
                  sessionId: "opencode-" + process.pid,
                  cwd: process.cwd(),
                  ...(extra || {}),
                });
                const child = spawn(REPORTER, ["opencode", "--event", event], {
                  detached: true,
                  stdio: ["pipe", "ignore", "ignore"],
                });
                child.on("error", () => {});
                child.stdin.on("error", () => {});
                child.stdin.end(payload);
                child.unref();
              } catch (_) {}
            }

            export const PedalsPresence = async () => {
              report("session-start");
              return {
                "tool.execute.before": async () => {
                  report("busy");
                },
                "permission.ask": async () => {
                  report("ask");
                },
                event: async ({ event }) => {
                  try {
                    if (!event) return;
                    if (event.type === "session.idle") report("stop");
                    if (event.type === "permission.replied") report("busy");
                  } catch (_) {}
                },
                dispose: async () => {
                  report("session-end");
                },
              };
            };
            """
            return Data((source + "\n").utf8)
        }

        static func install(reporterPath: String, home: URL) throws {
            try OwnedFile.install(
                canonical: canonicalData(reporterPath: reporterPath),
                path: path(home: home), marker: marker
            )
        }

        static func uninstall(home: URL) throws {
            try OwnedFile.uninstall(path: path(home: home), marker: marker)
        }

        static func state(reporterPath: String, home: URL) -> State {
            OwnedFile.state(
                canonical: canonicalData(reporterPath: reporterPath),
                path: path(home: home), marker: marker
            )
        }
    }

    // MARK: - omp / pi

    /// The omp and pi coding agents share one extension template
    /// (`~/.omp/agent/extensions/pedals/index.ts` /
    /// `~/.pi/agent/extensions/pedals/index.ts`); they differ in the import
    /// path and shutdown mapping. omp loads extensions into in-process
    /// subagent sessions, so a subagent's session_shutdown must not end the
    /// top-level record — the daemon pid sweep owns cleanup. pi extensions
    /// run only top-level, so its session_shutdown maps to session-end.
    enum PiFamily {
        static let marker = "/* pedals-managed-extension */"

        enum Variant: String {
            case omp
            case pi

            var dotDirectory: String { ".\(rawValue)" }

            var importPath: String {
                switch self {
                case .omp: "@oh-my-pi/pi-coding-agent"
                case .pi: "@mariozechner/pi-coding-agent"
                }
            }
        }

        static func path(home: URL, agent: Variant) -> String {
            home.appendingPathComponent(agent.dotDirectory, isDirectory: true)
                .appendingPathComponent("agent", isDirectory: true)
                .appendingPathComponent("extensions", isDirectory: true)
                .appendingPathComponent("pedals", isDirectory: true)
                .appendingPathComponent("index.ts").path
        }

        static func canonicalData(reporterPath: String, agent: Variant) -> Data {
            let reporter = escapeDoubleQuoted(reporterPath)
            let slug = agent.rawValue
            let shutdown: String
            switch agent {
            case .omp:
                shutdown = """
                  // omp loads extensions into in-process subagent sessions; a subagent
                  // shutdown must not end the top-level record. The daemon pid sweep
                  // owns session teardown, so session_shutdown is deliberately unmapped.
                """
            case .pi:
                shutdown = """
                  \(slug).on("session_shutdown", () => {
                    report("session-end");
                  });
                """
            }
            let source = """
            \(marker)
            // Generated by Pedals — `pedals hooks uninstall \(slug)` removes this file.
            import { spawn } from "node:child_process";
            import type { ExtensionAPI } from "\(agent.importPath)";

            const REPORTER = "\(reporter)";

            function report(event: string, extra?: Record<string, unknown>): void {
              try {
                const payload = JSON.stringify({
                  sessionId: "\(slug)-" + process.pid,
                  cwd: process.cwd(),
                  ...(extra ?? {}),
                });
                const child = spawn(REPORTER, ["\(slug)", "--event", event], {
                  detached: true,
                  stdio: ["pipe", "ignore", "ignore"],
                });
                child.on("error", () => {});
                child.stdin.on("error", () => {});
                child.stdin.end(payload);
                child.unref();
              } catch {}
            }

            // Last assistant text of the session, capped at ~1000 bytes.
            function lastAssistantText(ctx: any): string | undefined {
              try {
                const entries = ctx?.sessionManager?.getEntries?.();
                if (!Array.isArray(entries)) return undefined;
                for (let i = entries.length - 1; i >= 0; i--) {
                  const entry = entries[i];
                  const message = entry?.message;
                  if (entry?.type !== "message") continue;
                  if (message?.role !== "assistant") continue;
                  if (!Array.isArray(message.content)) continue;
                  const text = message.content
                    .filter((part: any) => part?.type === "text")
                    .map((part: any) => String(part.text ?? ""))
                    .join("")
                    .trim();
                  return text ? text.slice(0, 1000) : undefined;
                }
              } catch {}
              return undefined;
            }

            export default function (\(slug): ExtensionAPI) {
              report("session-start");
              \(slug).on("agent_start", () => {
                report("busy");
              });
              \(slug).on("agent_end", (_event: unknown, ctx: unknown) => {
                const message = lastAssistantText(ctx);
                report("stop", message ? { message } : undefined);
              });
            \(shutdown)
            }
            """
            return Data((source + "\n").utf8)
        }

        static func install(reporterPath: String, home: URL, agent: Variant) throws {
            try OwnedFile.install(
                canonical: canonicalData(reporterPath: reporterPath, agent: agent),
                path: path(home: home, agent: agent), marker: marker
            )
        }

        static func uninstall(home: URL, agent: Variant) throws {
            let filePath = path(home: home, agent: agent)
            try OwnedFile.uninstall(path: filePath, marker: marker)
            // The extensions/pedals/ directory is ours alone — remove it once
            // its owned file is gone (rmdir semantics: fails harmlessly if a
            // user parked anything else inside).
            let directory = URL(fileURLWithPath: filePath).deletingLastPathComponent().path
            if !FileManager.default.fileExists(atPath: filePath) {
                _ = rmdir(directory) // true rmdir: only removes when empty
            }
        }

        static func state(reporterPath: String, home: URL, agent: Variant) -> State {
            OwnedFile.state(
                canonical: canonicalData(reporterPath: reporterPath, agent: agent),
                path: path(home: home, agent: agent), marker: marker
            )
        }
    }
}
