import Foundation

/// Hermes: a generated Python plugin directory at
/// `~/.hermes/plugins/pedals-presence/` holding `plugin.yaml` and
/// `__init__.py`. Ownership lives in the `# pedals-managed-hook` marker on
/// the module's first line; install refuses to overwrite an unowned module,
/// uninstall removes the directory only when the module is owned, and state
/// requires BOTH files to byte-match (an orphaned or drifted plugin.yaml
/// reads as outdated).
///
/// Mapping: on_session_start → session-start, pre_llm_call → busy,
/// transform_llm_output → stop (message = response_text), on_session_end →
/// nothing (Hermes fires it per turn; the daemon pid sweep owns teardown).
extension HookInstaller {
    enum Hermes {
        static let marker = "# pedals-managed-hook"

        static func directory(home: URL) -> URL {
            home.appendingPathComponent(".hermes", isDirectory: true)
                .appendingPathComponent("plugins", isDirectory: true)
                .appendingPathComponent("pedals-presence", isDirectory: true)
        }

        static func yamlPath(home: URL) -> String {
            directory(home: home).appendingPathComponent("plugin.yaml").path
        }

        static func modulePath(home: URL) -> String {
            directory(home: home).appendingPathComponent("__init__.py").path
        }

        static let yamlData: Data = {
            let source = """
            \(marker)
            name: pedals-presence
            version: "1.0.0"
            description: Reports coding-agent activity to the Pedals daemon.
            author: Pedals
            hooks:
              - on_session_start
              - pre_llm_call
              - transform_llm_output
              - on_session_end
            provides_hooks:
              - on_session_start
              - pre_llm_call
              - transform_llm_output
              - on_session_end
            """
            return Data((source + "\n").utf8)
        }()

        static func moduleData(reporterPath: String) -> Data {
            let reporter = escapeDoubleQuoted(reporterPath)
            let source = """
            \(marker)
            \"\"\"Pedals presence plugin - generated by Pedals.

            `pedals hooks uninstall hermes` removes this directory. Every hook is
            inert on failure: it spawns the reporter detached, writes one small
            JSON payload to stdin, and swallows all errors.
            \"\"\"

            import json
            import os
            import subprocess

            _REPORTER = "\(reporter)"


            def _report(event, extra=None):
                try:
                    payload = {"sessionId": "hermes-%d" % os.getpid(), "cwd": os.getcwd()}
                    if extra:
                        payload.update(extra)
                    proc = subprocess.Popen(
                        [_REPORTER, "hermes", "--event", event],
                        stdin=subprocess.PIPE,
                        stdout=subprocess.DEVNULL,
                        stderr=subprocess.DEVNULL,
                    )
                    try:
                        proc.stdin.write(json.dumps(payload).encode("utf-8"))
                    finally:
                        proc.stdin.close()
                except Exception:
                    pass


            def on_session_start(**_kwargs):
                _report("session-start")
                return None


            def pre_llm_call(**_kwargs):
                _report("busy")
                return None


            def transform_llm_output(response_text=None, **_):
                message = response_text.strip() if isinstance(response_text, str) else ""
                _report("stop", {"message": message} if message else None)
                return None


            def on_session_end(**_kwargs):
                # Hermes fires on_session_end once per turn; the daemon pid sweep
                # owns real session teardown, so this is deliberately a no-op.
                return None


            def register(ctx):
                try:
                    ctx.register_hook("on_session_start", on_session_start)
                    ctx.register_hook("pre_llm_call", pre_llm_call)
                    ctx.register_hook("transform_llm_output", transform_llm_output)
                    ctx.register_hook("on_session_end", on_session_end)
                except Exception:
                    pass
            """
            return Data((source + "\n").utf8)
        }

        // MARK: - Lifecycle

        static func install(reporterPath: String, home: URL) throws {
            let manager = FileManager.default
            let pluginDirectory = directory(home: home)
            let module = modulePath(home: home)
            let yaml = yamlPath(home: home)

            if let existing = manager.contents(atPath: module) {
                guard OwnedFile.contains(existing, marker: marker) else {
                    throw InstallerError.unownedFile(path: module)
                }
            } else if manager.fileExists(atPath: yaml) {
                // A plugin.yaml with no owned module is someone else's plugin.
                throw InstallerError.unownedFile(path: yaml)
            }

            do {
                try manager.createDirectory(at: pluginDirectory, withIntermediateDirectories: true)
                try moduleData(reporterPath: reporterPath)
                    .write(to: URL(fileURLWithPath: module), options: .atomic)
                try yamlData.write(to: URL(fileURLWithPath: yaml), options: .atomic)
            } catch {
                // An orphaned plugin.yaml breaks Hermes at load: never leave a
                // partial plugin behind.
                try? manager.removeItem(at: pluginDirectory)
                throw error
            }
        }

        static func uninstall(home: URL) throws {
            let manager = FileManager.default
            guard let module = manager.contents(atPath: modulePath(home: home)),
                  OwnedFile.contains(module, marker: marker)
            else { return }
            try manager.removeItem(at: directory(home: home))
        }

        static func state(reporterPath: String, home: URL) -> State {
            let manager = FileManager.default
            guard let module = manager.contents(atPath: modulePath(home: home)) else {
                return .notInstalled
            }
            guard OwnedFile.contains(module, marker: marker) else { return .notInstalled }
            if module == moduleData(reporterPath: reporterPath),
               manager.contents(atPath: yamlPath(home: home)) == yamlData
            {
                return .installed
            }
            return .outdated
        }
    }
}
