import Foundation

/// Plugin-based agents whose hook surface is a generated source file Pedals
/// owns outright: opencode (JS plugin under Bun) and the omp/pi pair
/// (TypeScript extensions sharing one template). The generated code is inert
/// on failure — it spawns the reporter detached, writes one small JSON to
/// stdin, and swallows every error so it can never crash or block the host
/// agent. No env guard is needed: Pedals is system-wide.
extension HookInstaller {
    /// Rewrites only generated plugin files that already carry a Pedals
    /// ownership marker. App updates use this to deliver new event mappings
    /// without opting users into agents they never enabled.
    @discardableResult
    public static func refreshManagedGeneratedPluginInstallations(
        reporterPath: String,
        home explicitHome: URL? = nil
    ) throws -> [HookedAgent] {
        let home = explicitHome ?? defaultHome
        let candidates: [(HookedAgent, String, String)] = [
            (.opencode, OpenCode.path(home: home), OpenCode.marker),
            (.omp, PiFamily.path(home: home, agent: .omp), PiFamily.marker),
            (.pi, PiFamily.path(home: home, agent: .pi), PiFamily.marker),
        ]
        let managed = candidates.compactMap { agent, path, marker -> HookedAgent? in
            guard let data = FileManager.default.contents(atPath: path),
                  let text = String(data: data, encoding: .utf8),
                  text.contains(marker)
            else { return nil }
            return agent
        }
        for agent in managed {
            try install(for: agent, reporterPath: reporterPath, home: home)
        }
        return managed
    }

    // MARK: - opencode

    /// `~/.config/opencode/plugins/pedals-presence.js`. OpenCode exposes
    /// assistant message/part events, so the plugin keeps the newest
    /// assistant text and sends a throttled working update plus the complete
    /// text on session.idle.
    enum OpenCode {
        static let marker = "// pedals-managed-hook"

        static func path(home: URL) -> String {
            home.appendingPathComponent(".config", isDirectory: true)
                .appendingPathComponent("opencode", isDirectory: true)
                .appendingPathComponent("plugins", isDirectory: true)
                .appendingPathComponent("pedals-presence.js").path
        }

        static func canonicalData(reporterPath: String) -> Data {
            let reporter = escapeDoubleQuoted(reporterPath)
            let source = """
            \(marker)
            // Generated by Pedals — `pedals hooks uninstall opencode` removes this file.
            // opencode runs plugins under Bun; node:child_process gives us stdin control.
            import { spawn } from "node:child_process";

            const REPORTER = "\(reporter)";
            const FALLBACK_SESSION = "opencode-" + process.pid;
            const STREAM_INTERVAL_MS = 5000;
            const sessions = new Set();
            const assistantMessageSessions = new Map();
            const latestMessages = new Map();
            const lastStreamAt = new Map();

            function report(event, extra) {
              try {
                const sessionId = extra?.sessionId || FALLBACK_SESSION;
                sessions.add(sessionId);
                const payload = JSON.stringify({
                  sessionId,
                  cwd: process.cwd(),
                  ...(extra || {}),
                });
                const child = spawn(REPORTER, ["opencode", "--event", event], {
                  detached: true,
                  stdio: ["pipe", "ignore", "ignore"],
                });
                child.on("error", () => {});
                child.stdin.on("error", () => {});
                child.stdin.end(payload);
                child.unref();
              } catch (_) {}
            }

            function sessionId(value) {
              return value?.sessionID
                || value?.sessionId
                || value?.properties?.sessionID
                || value?.properties?.sessionId;
            }

            function rememberAssistantPart(event) {
              const part = event?.properties?.part;
              if (part?.type !== "text") return;
              const knownSession = assistantMessageSessions.get(part.messageID);
              if (!knownSession) return;
              const id = part.sessionID || knownSession;
              const message = String(part.text || "").trim();
              if (!message) return;
              latestMessages.set(id, message);
              const now = Date.now();
              if (now - (lastStreamAt.get(id) || 0) >= STREAM_INTERVAL_MS) {
                lastStreamAt.set(id, now);
                report("busy", { sessionId: id, message });
              }
            }

            export const PedalsPresence = async () => {
              return {
                "tool.execute.before": async (input) => {
                  report("busy", { sessionId: sessionId(input) || FALLBACK_SESSION });
                },
                "permission.ask": async (input) => {
                  report("ask", { sessionId: sessionId(input) || FALLBACK_SESSION });
                },
                event: async ({ event }) => {
                  try {
                    if (!event) return;
                    if (event.type === "session.created") {
                      const id = event.properties?.info?.id || sessionId(event);
                      if (id) report("session-start", { sessionId: id });
                    }
                    if (event.type === "message.updated") {
                      const info = event.properties?.info;
                      if (info?.role === "assistant" && info?.id && info?.sessionID) {
                        assistantMessageSessions.set(info.id, info.sessionID);
                        sessions.add(info.sessionID);
                      }
                    }
                    if (event.type === "message.part.updated") {
                      rememberAssistantPart(event);
                    }
                    if (event.type === "session.idle") {
                      const id = sessionId(event) || FALLBACK_SESSION;
                      const message = latestMessages.get(id);
                      report("stop", { sessionId: id, ...(message ? { message } : {}) });
                    }
                    if (event.type === "permission.asked") {
                      report("ask", {
                        sessionId: sessionId(event) || FALLBACK_SESSION,
                      });
                    }
                    if (event.type === "permission.replied") {
                      report("busy", {
                        sessionId: sessionId(event) || FALLBACK_SESSION,
                      });
                    }
                    if (event.type === "session.deleted") {
                      const id = event.properties?.info?.id || sessionId(event);
                      if (id) {
                        report("session-end", { sessionId: id });
                        sessions.delete(id);
                        latestMessages.delete(id);
                        lastStreamAt.delete(id);
                      }
                    }
                  } catch (_) {}
                },
                dispose: async () => {
                  for (const id of sessions) {
                    report("session-end", { sessionId: id });
                  }
                },
              };
            };
            """
            return Data((source + "\n").utf8)
        }

        static func install(reporterPath: String, home: URL) throws {
            try OwnedFile.install(
                canonical: canonicalData(reporterPath: reporterPath),
                path: path(home: home), marker: marker
            )
        }

        static func uninstall(home: URL) throws {
            try OwnedFile.uninstall(path: path(home: home), marker: marker)
        }

        static func state(reporterPath: String, home: URL) -> State {
            OwnedFile.state(
                canonical: canonicalData(reporterPath: reporterPath),
                path: path(home: home), marker: marker
            )
        }
    }

    // MARK: - omp / pi

    /// The omp and pi coding agents share one extension template
    /// (`~/.omp/agent/extensions/pedals/index.ts` /
    /// `~/.pi/agent/extensions/pedals/index.ts`); they differ in the import
    /// path and shutdown mapping. omp loads extensions into in-process
    /// subagent sessions, so a subagent's session_shutdown must not end the
    /// top-level record — the daemon pid sweep owns cleanup. pi extensions
    /// run only top-level, so its session_shutdown maps to session-end.
    enum PiFamily {
        static let marker = "/* pedals-managed-extension */"

        enum Variant: String {
            case omp
            case pi

            var dotDirectory: String { ".\(rawValue)" }

            var importPath: String {
                switch self {
                case .omp: "@oh-my-pi/pi-coding-agent"
                case .pi: "@mariozechner/pi-coding-agent"
                }
            }
        }

        static func path(home: URL, agent: Variant) -> String {
            home.appendingPathComponent(agent.dotDirectory, isDirectory: true)
                .appendingPathComponent("agent", isDirectory: true)
                .appendingPathComponent("extensions", isDirectory: true)
                .appendingPathComponent("pedals", isDirectory: true)
                .appendingPathComponent("index.ts").path
        }

        static func canonicalData(reporterPath: String, agent: Variant) -> Data {
            let reporter = escapeDoubleQuoted(reporterPath)
            let slug = agent.rawValue
            let shutdown: String
            switch agent {
            case .omp:
                shutdown = """
                  // omp loads extensions into in-process subagent sessions; a subagent
                  // shutdown must not end the top-level record. The daemon pid sweep
                  // owns session teardown, so session_shutdown is deliberately unmapped.
                """
            case .pi:
                shutdown = """
                  \(slug).on("session_shutdown", () => {
                    report("session-end");
                  });
                """
            }
            let source = """
            \(marker)
            // Generated by Pedals — `pedals hooks uninstall \(slug)` removes this file.
            import { spawn } from "node:child_process";
            import type { ExtensionAPI } from "\(agent.importPath)";

            const REPORTER = "\(reporter)";
            const STREAM_INTERVAL_MS = 5000;
            let lastStreamAt = 0;

            function report(event: string, extra?: Record<string, unknown>): void {
              try {
                const payload = JSON.stringify({
                  sessionId: "\(slug)-" + process.pid,
                  cwd: process.cwd(),
                  ...(extra ?? {}),
                });
                const child = spawn(REPORTER, ["\(slug)", "--event", event], {
                  detached: true,
                  stdio: ["pipe", "ignore", "ignore"],
                });
                child.on("error", () => {});
                child.stdin.on("error", () => {});
                child.stdin.end(payload);
                child.unref();
              } catch {}
            }

            function assistantText(message: any): string | undefined {
              try {
                if (message?.role !== "assistant") return undefined;
                if (!Array.isArray(message.content)) return undefined;
                const text = message.content
                  .filter((part: any) => part?.type === "text")
                  .map((part: any) => String(part.text ?? ""))
                  .join("")
                  .trim();
                return text ? text.slice(0, 1000) : undefined;
              } catch {}
              return undefined;
            }

            // Last assistant text of the session, capped at ~1000 bytes.
            function lastAssistantText(ctx: any): string | undefined {
              try {
                const entries = ctx?.sessionManager?.getEntries?.();
                if (!Array.isArray(entries)) return undefined;
                for (let i = entries.length - 1; i >= 0; i--) {
                  const entry = entries[i];
                  const message = entry?.message;
                  if (entry?.type !== "message") continue;
                  const text = assistantText(message);
                  if (text) return text;
                }
              } catch {}
              return undefined;
            }

            export default function (\(slug): ExtensionAPI) {
              report("session-start");
              \(slug).on("agent_start", () => {
                report("busy");
              });
              \(slug).on("message_update", (event: any) => {
                const message = assistantText(event?.message);
                const now = Date.now();
                if (message && now - lastStreamAt >= STREAM_INTERVAL_MS) {
                  lastStreamAt = now;
                  report("busy", { message });
                }
              });
              \(slug).on("agent_end", (_event: unknown, ctx: unknown) => {
                const message = lastAssistantText(ctx);
                report("stop", message ? { message } : undefined);
              });
            \(shutdown)
            }
            """
            return Data((source + "\n").utf8)
        }

        static func install(reporterPath: String, home: URL, agent: Variant) throws {
            try OwnedFile.install(
                canonical: canonicalData(reporterPath: reporterPath, agent: agent),
                path: path(home: home, agent: agent), marker: marker
            )
        }

        static func uninstall(home: URL, agent: Variant) throws {
            let filePath = path(home: home, agent: agent)
            try OwnedFile.uninstall(path: filePath, marker: marker)
            // The extensions/pedals/ directory is ours alone — remove it once
            // its owned file is gone (rmdir semantics: fails harmlessly if a
            // user parked anything else inside).
            let directory = URL(fileURLWithPath: filePath).deletingLastPathComponent().path
            if !FileManager.default.fileExists(atPath: filePath) {
                _ = rmdir(directory) // true rmdir: only removes when empty
            }
        }

        static func state(reporterPath: String, home: URL, agent: Variant) -> State {
            OwnedFile.state(
                canonical: canonicalData(reporterPath: reporterPath, agent: agent),
                path: path(home: home, agent: agent), marker: marker
            )
        }
    }
}
